### ISSUE TITLE
natsort.c:29: warning: "_GNU_SOURCE" redefined

### ISSUE THREAD

**Issue by tueddy** [sourcefrog/natsort#14]
While compiling your library with PlatformIO (ESP32) &these compiler flags:

```
build_flags =
    -std=c++17
    -std=gnu++17
    -Wall
    -Wextra
    -Wunreachable-code
```

I get some warnings:
```
.pio/libdeps/lolin_d32_pro_sdmmc_pe/natsort/natsort.c:29: warning: "_GNU_SOURCE" redefined
   29 | #define _GNU_SOURCE
      |
<command-line>: note: this is the location of the previous definition
.pio/libdeps/lolin_d32_pro_sdmmc_pe/natsort/natsort.c: In function 'main':
.pio/libdeps/lolin_d32_pro_sdmmc_pe/natsort/natsort.c:137:26: warning: implicit declaration of function 'getline' [-Wimplicit-function-declaration]
  137 |           if ((linelen = getline(&line, &bufsize, stdin)) <= 0)
      |                          ^~~~~~~

```
Any way to get rid this issue? Thanks!

**Comment by sourcefrog** [comment]
If this is already defined by your environment then I'd suggest just cutting it out of the source.

**Comment by tueddy** [comment]
Thank's for your answer!
What about changing your code to 

```
#ifndef _GNU_SOURCE
    #define _GNU_SOURCE
#endif
```

This would fix at least the first warning.

**Comment by tueddy** [comment]
Thanks for merging!
The other warnings cannot be fixed because ESP-32 <stdio.h> has no getline() definition. I think it's s an ESP-32 platform issue

**Comment by sourcefrog** [comment]
As I guess you realized, getline is only needed for the CLI tool; if you want the strnatcmp function to link into your own program then it should not matter.
